### ISSUE TITLE
👋 

### ISSUE THREAD

**Issue by andrewwylde** [AlexanderEllis/daily-logger#1]
👋 
👁 👨‍💻 🏃 
🚫 💻 
❓ 

💯

**Comment by AlexanderEllis** [comment]
Hi @codelemur, 

Thank you for bringing this to my attention!  At this point, I haven't created the mobile version of this app yet.  I plan to get something together with React Native so that you can access it without your computer.

Alternatively, if this is something you're interested in, a PR would be very welcome!

Thanks!
